#!/bin/sh
#
# Copyright (C) 2018, TQ Systems
#

set -e

LED=/sys/class/leds/energymanager:green:network

echo netdev >$LED/trigger
echo br0 >$LED/device_name
echo 1 >$LED/link
echo 1 >$LED/rx
echo 1 >$LED/tx
