---
include:
- project: tq-em/build/docker/base-ci
  file: rules.yml
  ref: master

# Attention: Do not define trigger variables in the global section,
# this may lead to unexpected behavior in the triggered project.
.set-local-conf:
  variables:
    INTERNAL_META_EMOS_BRANCH: $CI_COMMIT_REF_NAME
    INTERNAL_META_EMOS_REF: $CI_COMMIT_SHA
    OVERRIDE_LOCAL_CONF: $INTERNAL_LOCAL_CONF

Trigger Core Snapshots:
  extends:
    - .rule-include-default-branch
    - .set-local-conf
  trigger:
    project: tq-em/build/docker/yocto-scripts
    strategy: depend

Trigger Core QA Snapshots:
  extends:
    - .rule-include-default-branch
    - .set-local-conf
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend

Trigger Core QA Tests:
  extends:
    - .rule-include-merge-request-for-default-branch
    - .set-local-conf
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend
  variables:
    RUN_INTEGRATION_TESTS: 'true'
    RUN_OPENVAS_SCAN: 'true'
    GIT_REFERENCE: meta-emos_$CI_COMMIT_SHORT_SHA
