---
include:
- project: tq-em/build/docker/base-ci
  file: rules.yml
  ref: master

# Attention: Do no define variables in the global section here,
# this leads to unexpected behavior in the triggered project,
# e.g. the wrong gitlab-runner tag is used.
.common-variables:
  variables:
    INTERNAL_META_EMOS_BRANCH: $CI_COMMIT_REF_NAME
    INTERNAL_META_EMOS_REF: $CI_COMMIT_SHA
    OVERRIDE_LOCAL_CONF: $INTERNAL_LOCAL_CONF

Trigger Core Snapshots:
  extends:
    - .common-variables
    - .rule-include-default-branch
  trigger:
    project: tq-em/build/yocto-scripts
    strategy: depend

Trigger Core QA Snapshots:
  extends:
    - .common-variables
    - .rule-include-default-branch
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend

Trigger Core QA Tests:
  extends:
    - .common-variables
    - .rule-include-merge-request-for-default-branch
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend
  variables:
    RUN_INTEGRATION_TESTS: 'true'
