---
include:
- project: tq-em/build/docker/base
  file: ci/include.yml
  ref: master

# Attention: Do not define trigger variables in the global section,
# this may lead to unexpected behavior in the triggered project.
.internal-build-variables:
  variables:
    INTERNAL_META_EMOS_BRANCH: $CI_COMMIT_REF_NAME
    INTERNAL_META_EMOS_REF: $CI_COMMIT_SHA
    GITLAB_RUNNER_TAG: 'tq-em-yocto-fast'

.internal-meta-emos-conf:
  variables:
    OVERRIDE_LOCAL_CONF: $INTERNAL_LOCAL_CONF

.product-qualification-conf:
  variables:
    OVERRIDE_LOCAL_CONF: $PQT_LOCAL_CONF

Gitleaks:
  extends: .gitleaks

Trigger Core Snapshots:
  extends:
    - .rule-include-default-branch
    - .internal-build-variables
    - .internal-meta-emos-conf
  trigger:
    project: tq-em/build/docker/yocto-scripts
    strategy: depend

Trigger Core QA Snapshots:
  extends:
    - .rule-include-default-branch
    - .internal-build-variables
    - .internal-meta-emos-conf
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend

Trigger Core QA Tests:
  extends:
    - .rule-include-merge-request-for-default-branch
    - .internal-build-variables
    - .internal-meta-emos-conf
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend
  variables:
    RUN_INTEGRATION_TESTS: 'true'
    RUN_OPENVAS_SCAN: 'true'
    GIT_REFERENCE: meta-emos_$CI_COMMIT_SHORT_SHA

Trigger Core PQT Tests:
  extends:
    - .rule-include-merge-request-for-default-branch
    - .internal-build-variables
    - .product-qualification-conf
  trigger:
    project: tq-em/build/yocto/core-pqt-bundle
    strategy: depend
  variables:
    RUN_INTERFACE_TESTS: 'true'
