variables:
  # INTERNAL_META_EMOS_BRANCH: $CI_COMMIT_REF_NAME
  INTERNAL_META_EMOS_BRANCH: feature/refactor-sdk
  OVERRIDE_LOCAL_CONF: $INTERNAL_LOCAL_CONF

Trigger Integration Test:
  trigger:
    project: tq-em/build/yocto/core-qa-bundle
    strategy: depend
    branch: initial
  # rules:
  #   - if: >
  #       $CI_PIPELINE_SOURCE == "merge_request_event"
  #         && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
  variables:
    RUN_INTEGRATION_TESTS: 'true'

Trigger Core Snapshots:
  trigger:
    project: tq-em/build/yocto-scripts
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
