#!/bin/sh
# Copyright (C) 2018 TQ-Systems GmbH
#
# Licensed under GPLv2 or later.
#

case "$1" in
        get)            [ -n "$2" ] && fw_printenv $2 2> /dev/null | cut -d '=' -f 2- ;;
        set)            fw_setenv ${2%%=*} ${2#*=} ;;
        unset)          fw_setenv $2 ;;
        show)           fw_printenv ;;
        *)
                echo "usage: nvram [get name] [set name=value] [unset name] [show]"
                ;;
esac
