# SPDX-License-Identifier: MIT
#
# Copyright (C) 2024 TQ-Systems GmbH <oss@ew.tq-group.com>, D-82229 Seefeld, Germany.
# Author: Matthias Schiffer

#@TYPE: Machine
#@NAME: TQ-Systems EM (AArch64)
#@DESCRIPTION: Combined machine configuration for AArch64-based TQ-Systems Energy Manager

MACHINEOVERRIDES =. "em:"

require conf/machine/include/arm/arch-arm64.inc

# Multiconfigs can be disabled via local.conf to reduce build time and required disk space
EM_AARCH64_em4xx ?= "1"
EM_AARCH64_eg4xx ?= "1"

# oe.utils.ifelse and oe.types.boolean are not available here, but bb.utils is
MACHINEOVERRIDES =. "${@ 'em-with-em4xx:' if bb.utils.to_boolean(d.getVar('EM_AARCH64_em4xx')) else '' }"
MACHINEOVERRIDES =. "${@ 'em-with-eg4xx:' if bb.utils.to_boolean(d.getVar('EM_AARCH64_eg4xx')) else '' }"

PREFERRED_PROVIDER_virtual/kernel = "linux-em"
PREFERRED_PROVIDER_virtual/bootloader = "em-aarch64-bootloader"

KERNEL_DEVICETREE = " \
    freescale/imx8mn-eg4xx.dtb \
    freescale/imx8mn-em4xx-l-ksz8863.dtb \
    freescale/imx8mn-em4xx-l-mv88e6020.dtb \
    freescale/imx8mn-em4xx-u.dtb \
"

KERNEL_IMAGETYPE = "Image.gz"

# Console information is taken from cmdline/DTB. SERIAL_CONSOLES is set to " "
# to make it non-empty, resulting in serial-getty@.service to be installed,
# thus allowing systemd's console auto detection to work.
SERIAL_CONSOLES = " "
USE_VT = "0"

MACHINE_FEATURES = "ext2 vfat"

TQ_DEVICE_TYPE = "hw02xx"
TQ_DEVICE_SUBTYPE = '{"tq,em4xx": "hw0200", "tq,imx8mn-eg4xx": "hw0220"}'
TQ_PRODUCT_ID = '{"tq,em4xx": 18530, "tq,imx8mn-eg4xx": 18562}'

EM_BUNDLE_BOOTLOADER = ""
EM_BUNDLE_BOOTLOADER:append:em-with-em4xx = " \
    tq_em4xx_512m \
    tq_em4xx_1024m \
"
EM_BUNDLE_BOOTLOADER:append:em-with-eg4xx = " \
    tq_imx8mn-eg4xx_512m \
"
EM_BUNDLE_BOOTLOADER[tq_em4xx_512m] = "bootloader-em4xx-512m.bin"
EM_BUNDLE_BOOTLOADER[tq_em4xx_1024m] = "bootloader-em4xx-1g.bin"
EM_BUNDLE_BOOTLOADER[tq_imx8mn-eg4xx_512m] = "bootloader-eg4xx-512m.bin"

MACHINE_EXTRA_RRECOMMENDS += " \
    eol-led \
    status-led \
    netdev-led \
    em-power-handler \
    teridiand-config \
    em-timesync \
    linux-firmware-imx-sdma-imx7d \
    em-aarch64-bootloader-env \
"

BBMULTICONFIG:append:em-with-em4xx = " em4xx"
BBMULTICONFIG:append:em-with-eg4xx = " eg4xx"

MULTICONFIG_VARS += "DEPLOY_DIR_IMAGE LICENSE_DIRECTORY PREFERRED_PROVIDER_virtual/bootloader"
INHERIT += "multiconfig-vars"
