#!/bin/sh

export PATH=/usr/bin:/bin:/usr/sbin:/sbin


fatal() {
	echo >&2 "$1"
	exit 1
}


[ $$ -eq 1 ] || fatal 'emos-init must run as PID1.'


[ -e /dev/console ] || mount -t devtmpfs devtmpfs /dev || fatal '/dev mount failed.'

# Initialize stdout and stderr
exec >/dev/console 2>/dev/console

mount -t proc proc /proc || fatal '/proc mount failed.'
mount -t sysfs sysfs /sys || fatal '/sys mount failed.'

mount -o ro /dev/mmcblk0p9 /auth || fatal '/auth mount failed.'
mount /dev/mmcblk0p6 /update || fatal '/update mount failed.'
mount /dev/mmcblk0p7 /cfglog || fatal '/cfglog mount failed.'

mkdir -p /cfglog/etc /cfglog/work || fatal 'Unable to create required overlayfs directories.'
mount -t overlay \
	-o lowerdir=/auth/etc:/etc,upperdir=/cfglog/etc,workdir=/cfglog/work \
	overlay /etc || fatal '/etc overlay mount failed.'

mount /dev/mmcblk0p8 /data || fatal '/data mount failed.'
mount /dev/mmcblk0p5 /apps || fatal '/apps mount failed.'


if command -v empkg >/dev/null; then
        # Sync new preinstalled apps in rootfs to appfs
        empkg --no-lock --no-systemd sync
fi


exec /lib/systemd/systemd
