#!/bin/sh

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

DEV_APPS=/dev/mmcblk0p5
DEV_UPDATE=/dev/mmcblk0p6
DEV_CFGLOG=/dev/mmcblk0p7
DEV_DATA=/dev/mmcblk0p8
DEV_AUTH=/dev/mmcblk0p9

haveged_running=false

MOUNT_OPTS_RO="nosuid,nodev,ro"
MOUNT_OPTS_RW="nosuid,nodev,noatime"


fatal() {
	echo >&2 "$1"
	exit 1
}

add_config() {
	local file="$1"
	local src="/cfglog/system/${file}" dest="/etc/${file}"
	mount --bind "$src" "$dest" || fatal "Failed to bind ${src}."
}

start_haveged() {
	$haveged_running || haveged
	haveged_running=true
}

stop_haveged() {
	if $haveged_running; then
		killall haveged
		haveged_running=false
	fi
}

check_flag() {
	if [ -e "/update/$1" ]; then
		echo 'true'
	else
		echo 'false'
	fi
}

factory_reset() {
	local reset_data=$1

	# Gather entropy for mkfs.ext4
	start_haveged

	mkfs.ext4 -Fvj $DEV_APPS
	mkfs.ext4 -Fvj $DEV_CFGLOG

	if $reset_data; then
		mkfs.ext4 -Fvj $DEV_DATA

		mount -t tmpfs apps /apps
		mkdir /apps/installed
		mount --bind /opt/apps /apps/installed

		local TBIN=/apps/installed/teridiand/bin

		# Reset teridian registers
		if [ -x $TBIN/tboot ]; then
			$TBIN/tboot
			$TBIN/tcmd SPI_CMD_CLEAR_REGISTERS
		fi

		umount /apps/installed
		umount /apps
	fi
}

data_reset() {
	echo >&2 'Formatting /data.'

	# Gather entropy for mkfs.ext4
	start_haveged

	mkfs.ext4 -Fvj $DEV_DATA
}

update_reset() {
	echo >&2 'Formatting /update.'

	# Gather entropy for mkfs.ext4
	start_haveged

	mkfs.ext4 -Fvj $DEV_UPDATE
}

backup_restore() {
	tar -C / -xzf /update/backup.tar.gz
}

# Delete files that may not be restored from backups
# (because they constitute a security risk)
backup_sanitize() {
	rm -f /cfglog/system/password
}


[ $$ -eq 1 ] || fatal 'em-init must run as PID1.'


[ -e /dev/console ] || mount -t devtmpfs devtmpfs /dev || fatal '/dev mount failed.'

# Initialize stdout and stderr
exec >/dev/console 2>/dev/console

mount -t proc proc /proc || fatal '/proc mount failed.'
mount -t sysfs sysfs /sys || fatal '/sys mount failed.'
mount -t tmpfs -o nosuid,nodev,mode=755 run /run || fatal '/run mount failed.'

# End of life status
END_OF_LIFE=false
mkdir -p /run/lock

if [ "$(fw_printenv -n END_OF_LIFE 2>/dev/null)" = "1" ]; then
	END_OF_LIFE=true
fi

# Mount eMMC partitions

# This check handles power loss during factory reset.
# As /update is formatted last, there are two possiblities for unfinished
# factory resets:
# 1) /update is not formatted yet. In this case, /update can still be mounted
#    and /update/factory-reset exists. The factory reset will be repeated on the
#    next boot.
# 2) /update is in the process of being formatted when the factory reset occurs.
#    In this case, the following mount may fail. In result, /update will be
#    formatted again, completing the factory reset.
if ! mount -o $MOUNT_OPTS_RW $DEV_UPDATE /update; then
	update_reset
	mount -o $MOUNT_OPTS_RW $DEV_UPDATE /update || fatal '/update mount failed.'
fi

FACTORY_RESET=$(check_flag factory-reset)

if $FACTORY_RESET && ! $END_OF_LIFE; then
	echo >&2 'Performing factory reset.'

	factory_reset true

	umount /update
	update_reset
	mount -o $MOUNT_OPTS_RW $DEV_UPDATE /update || fatal '/update mount failed.'
fi

SAFE_MODE=$(check_flag safe-mode)
BACKUP_RESTORE=$(check_flag backup-restore)

if $BACKUP_RESTORE && ! $END_OF_LIFE; then
	echo >&2 'Restoring backup.'

	factory_reset false
fi

mount -o $MOUNT_OPTS_RO $DEV_AUTH /auth || fatal '/auth mount failed.'
mount -o $MOUNT_OPTS_RW $DEV_CFGLOG /cfglog || fatal '/cfglog mount failed.'

if $BACKUP_RESTORE  && ! $END_OF_LIFE; then
	backup_restore
	backup_sanitize

	umount /update
	update_reset
	mount -o $MOUNT_OPTS_RW $DEV_UPDATE /update || fatal '/update mount failed.'
fi

if ! mount -o $MOUNT_OPTS_RW $DEV_DATA /data; then
	# When a backup import was interrupted while /data was being formatted,
	# the mount may fail. Rather than failing to boot, we will just try to
	# format it again.
	# To avoid formatting /data in other cases (potentially leading to data
	# loss), we only do so when the safe-mode, but not backup-restore is
	# set.
	# As long as backup-restore is not set, /update will not be formatted,
	# so we don't lose the safe-mode flag, indicating a failed backup
	# restore.
	$SAFE_MODE && ! $BACKUP_RESTORE || fatal '/data mount failed.'

	data_reset
	mount -o $MOUNT_OPTS_RW $DEV_DATA /data || fatal '/data mount failed.'
fi

mount -o $MOUNT_OPTS_RW $DEV_APPS /apps || fatal '/apps mount failed.'

stop_haveged

mkdir -p /run/lock

# Initialize default config
emcfg init

# Writable (simple) configuration files
add_config machine-id
add_config hostname

if command -v empkg >/dev/null; then
	if $END_OF_LIFE; then
		# This file is written once in EOL mode and indicates whether an EOL has been reached
		touch "/update/end_of_life"
		empkg --no-systemd --set-eol sync
	else
		# Sync new preinstalled apps in rootfs to appfs
		empkg --no-systemd sync
	fi
fi

exec /lib/systemd/systemd
