#!/bin/sh

CERTPATH="$1"
CERTDIR="$(dirname "$CERTPATH")"

KEYFILE="$CERTPATH.key"
CERTFILE="$CERTPATH.crt"

CONFFILE="/etc/ssl/openssl-em.cnf"

SUBJ="/CN=$(hostname).local"

if [ -s "$KEYFILE" -a -s "$CERTFILE" ]; then
	exit 0
fi

mkdir -p "$CERTDIR"
faketime @0 openssl req -x509 -config "$CONFFILE" -batch -subj "$SUBJ" -newkey rsa:2048 -keyout "$KEYFILE" -out "$CERTFILE" -days 36525 -nodes
