#!/bin/sh

set -e

PWFILE='/auth/etc/shadow'
LOCALPWFILE='/cfglog/system/password'

OUTDIR='/run/em/etc'
OUTFILE="$OUTDIR/shadow"

if [ -r "$LOCALPWFILE" ]; then
	PWFILE="$LOCALPWFILE"
fi


mkdir -p "$OUTDIR"

umask 077

awk '
	BEGIN {
		FS=":"
		OFS=":"
		rootpw="!"
	}

	/^root:/ {
		rootpw=$2
	}

	END {
		while ((getline < "/etc/shadow") > 0) {
			if ($1 == "root")
				$2 = rootpw

			print $0
		}
	}
' <"$PWFILE" >"$OUTFILE".tmp

# Rather than moving the file, we just copy the contents, so
# we don't break the bind mount to /etc/shadow
cat "$OUTFILE".tmp > "$OUTFILE"
rm "$OUTFILE".tmp
