#!/bin/sh

CONFIG='/cfglog/system/ntp.json'
WANTDIR="$1/sysinit.target.wants"
SERVICE='systemd-timesyncd.service'

if [ -r "$CONFIG" ]; then
	jq -e '.enable' <"$CONFIG" >/dev/null || exit 0
fi

mkdir -p "$WANTDIR" || exit 1
ln -s "/lib/systemd/system/$SERVICE" "$WANTDIR/"

exit 0
