#!/bin/sh

# Copyright (C) 2020,2025 TQ-Systems GmbH
# Author: Matthias Schiffer, Gregor Herburger
#
# Automatically disable power on fault (overcurrent), enable again after 1s

set -e

POWEROFF_TIME='1s'

POWER_GPIO='energymanager:vbus:enable'
FAULT_GPIO='energymanager:vbus:fault#'

while true; do
	gpiomon -e falling -s -n 1 $FAULT_GPIO & FAULT_PID=$!
	sleep 1
	gpioset $POWER_GPIO=1 & POWER_PID=$!

	wait $FAULT_PID
	echo >&2 'Power fault deteced, disabling for 1s'
	kill $POWER_PID; wait $POWER_PID || true
	gpioset --hold-period=$POWEROFF_TIME -t0 $POWER_GPIO=0

	echo >&2 'Enabling power again'
done
