defaults:
  url: https://packages.tq-group.com/energymanager/apps/{app}/{name}_{version}_{arch}.empkg

apps:
  backup:
    version: '1.1.8'

  button-handler:
    version: '2.2.4'

  data-transfer:
    version: '3.6.5'

  device-settings:
    version: '4.3.8'

  flash-scan:
    version: '2.2.5'

  health-check:
    version: '2.1.5'

  teridiand:
    version: '1.8.4'

  teridiand-fw:
    arch: 'all'
    version: '1.3.1'

  updater:
    version: '1.10.14'

  web-application:
    arch: 'all'
    version: '3.4.3'

  web-login:
    version: '3.0.5'
