defaults:
  url: https://packages.tq-group.com/energymanager/apps/{app}/{name}_{version}_{arch}.empkg

apps:
  backup:
    version: '1.0.2'

  button-handler:
    version: '2.2.0'

  data-transfer:
    version: '3.6.0'

  device-settings:
    version: '3.3.13'

  flash-scan:
    version: '2.2.0'

  health-check:
    version: '1.6.1'

  teridiand:
    version: '1.8.0'

  teridiand-fw:
    arch: 'all'
    version: '1.1.0'

  updater:
    version: '1.5.1'

  web-application:
    arch: 'all'
    version: '2.14.4'

  web-login:
    version: '2.5.0'
