defaults:
  url: http://packages.tq-group.com/energymanager/apps/{app}/{name}_{version}_{arch}.empkg

apps:
  button-handler:
    #version: ''
    #sha256[armv5e]: ''

  data-transfer:
    #version: ''
    #sha256[armv5e]: ''

  device-settings:
    #version: ''
    #sha256[armv5e]: ''

  flash-scan:
    #version: ''
    #sha256[armv5e]: ''

  health-check:
    #version: ''
    #sha256[armv5e]: ''

  teridiand:
    #version: ''
    #sha256[armv5e]: ''

  teridiand-fw:
    #version: ''
    #sha256[armv5e]: ''

  upnp:
    #version: ''
    #sha256[armv5e]: ''

  web-application:
    name: web-application-tq
    #version: ''
    #sha256[armv5e]: ''

  web-login:
    #version: ''
    #sha256[armv5e]: ''
