#!/bin/sh
#
# (c) Gateware Communications GmbH, Nuremberg 2017
#
# This script waits for link status changes on port 1 or port 2 of a Micrel
# KSZ8863 switch and updates the netdev LED trigger configuration.
#

set -e


MICREL=/apps/installed/micrel-switch-tool/bin/micrel


[ -x $MICREL ] || exit 0


GPIO_CHIP=0
GPIO_INTR=6


# Enable "P1 or P2 link change" interrupt
$MICREL smi 0xBB 0x80


handle_change() {
	local restart="$1"

	# Clear all interrupts (w1c)
	$MICREL smi 0xBC 0xFF

	# Read MII Basic Status register of port 1 and port 2
	local reg1=$($MICREL --raw mdio 1 1)
	local reg2=$($MICREL --raw mdio 2 1)
	local status=$(( ($reg1 | $reg2) & 0x4 ))
	if [ $status -eq 4 ]; then
		if $restart; then
			systemctl restart systemd-networkd.service
		fi
	else
		ip link set eth0 down
	fi
}


# gpiomon will print a newline for each falling edge
gpiomon -b -f -F '' $GPIO_CHIP $GPIO_INTR | (
	# Do not restart networkd on the initial run
	handle_change false

	while read; do
		handle_change true
	done
)
