#!/bin/sh

#
# Copyright (C) 2018-2019, TQ Systems
#

set -e


usage() {
	echo >&2 "Usage: emos-upgrade install BUNDLE"
	exit 1
}

cmd_install() {
	[ $# -eq 1 -a -e "$1" ] || usage

	emos-upgrade-status set_status update_1_started

	trap 'emos-upgrade-status reset' EXIT

	logger -t emos-upgrade "Starting system upgrade (currently running boot slot $(emos-upgrade-status get_slot_saved))"

	rauc install "$1"
	mv "$1" /update/last-upgrade.raucb
	emos-upgrade-status set_status update_1_finished

	trap - EXIT

	sleep 3
	reboot
}


CMD="$1"; shift

case "$CMD" in
install)
	cmd_$CMD "$@"
	;;

*)
	usage
esac
