#!/bin/sh

#
# Copyright (C) 2018-2020, TQ Systems
#

set -e

on_exit() {
	logger -t emos-upgrade-finalize 'resetting upgrade status'
	rm -f /update/*.raucb
	emos-upgrade-status reset
}

trap on_exit EXIT


OTHER_SLOT="$(emos-upgrade-status get_slot_other)"
OTHER_DEVICE="$(emos-upgrade-status get_slot_device "$OTHER_SLOT")"

logger -t emos-upgrade-finalize "clearing partition '$OTHER_DEVICE'"
rauc status mark-bad other
cat /dev/zero >"$OTHER_DEVICE" 2>/dev/null || true
