#!/bin/sh

#
# Copyright (C) 2018-2020, TQ-Systems GmbH
#

set -e


usage() {
	echo >&2 "Usage: emos-upgrade install [--no-reboot] BUNDLE"
	exit 1
}

cmd_install() {
	local OPT_REBOOT=true
	local arg

	while [ "${1:0:1}" = '-' ]; do
		arg="$1"; shift
		case "$arg" in
		--no-reboot)
			OPT_REBOOT=false
			;;

		*)
			usage
			exit 1
		esac
	done

	[ $# -eq 1 ] || usage

	local file="$1"
	if [ ! -e "$file" ]; then
		echo >&2 "Upgrade bundle '$file' not found."
		exit 1
	fi

	emos-upgrade-status set_status update_1_started

	trap 'emos-upgrade-status reset' EXIT

	logger -t emos-upgrade "Starting system upgrade (currently running boot slot $(emos-upgrade-status get_slot_active))"

	rauc install "$file"
	rm -f "$file"
	emos-upgrade-status set_status update_1_finished

	trap - EXIT

	if $OPT_REBOOT; then
		sleep 3
		reboot
	fi
}


CMD="$1"; shift

case "$CMD" in
install)
	cmd_$CMD "$@"
	;;

*)
	usage
esac
